validate the deployment on the basisof resource group

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,7 +16,6 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -29,33 +28,50 @@ jobs:
       - name: Login to Azure
         run: |
           az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
-          # Check if service principal exists
-          az ad sp show --id ${{ secrets.AZURE_CLIENT_ID }}
 
       - name: Install Bicep CLI
         run: az bicep install
 
-      - name: Generate Unique Solution Prefix and Environment Name
+      - name: Generate Resource Group Name
+        id: generate_rg_name
+        run: |
+          echo "Generating a unique resource group name..."
+          TIMESTAMP=$(date +%Y%m%d%H%M%S)
+          COMMON_PART="pslautomationRes"
+          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
+          echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
+      
+      - name: Check and Create Resource Group
+        id: check_create_rg
+        run: |
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "false" ]; then
+            echo "Resource group does not exist. Creating..."
+            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location northcentralus || { echo "Error creating resource group"; exit 1; }
+          else
+            echo "Resource group already exists."
+          fi
+
+      - name: Generate Unique Solution Prefix
         id: generate_solution_prefix
         run: |
           set -e
-          COMMON_PART="pslc"
+          COMMON_PART="pslr"
           TIMESTAMP=$(date +%s)  
           UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
           UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
-          ENVIRONMENT_NAME="env-${UNIQUE_SOLUTION_PREFIX}"  # Dynamically generated environment name
           echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
-          echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}" >> $GITHUB_ENV
-          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}, ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}"
+          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
 
-      - name: Deploy ARM Template at Subscription Level
+      - name: Deploy Bicep Template
         id: deploy
         run: |
           set -e
-          echo "Deploying arm template at the subscription level...."
-          az deployment sub create \
-            --location WestUS \
-            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
+          az deployment group create \
+            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
             --template-file infrastructure/deployment.json \
             --parameters \
                 HostingPlanName="${{ env.SOLUTION_PREFIX }}-plan" \
@@ -63,63 +79,118 @@ jobs:
                 WebsiteName="webapp-${{ env.SOLUTION_PREFIX }}" \
                 CosmosDBName="db-cosmos-${{ env.SOLUTION_PREFIX }}" \
                 CosmosDBRegion="NorthCentralUS" \
-                location="WestUS" \
                 AzureSearchService="search-${{ env.SOLUTION_PREFIX }}" \
                 AzureOpenAIResource="aoai-${{ env.SOLUTION_PREFIX }}" \
                 WorkspaceName="worksp-${{ env.SOLUTION_PREFIX }}" 
-            --output json
 
-          # Extract the webapp name from JSON response using jq
-          webapp_name=$(echo $deployment_output | jq -r .)
-          echo "webapp_name=$webapp_name" >> $GITHUB_ENV
-          echo "Deployment completed with webapp_name: $webapp_name"
-
-      - name: List KeyVaults and Store in Array
-        id: list_keyvaults
+      - name: Wait for Resource Deletion to Complete
         run: |
-          set -e
-          echo "Listing all KeyVaults in the subscription..."
+          # List of resources to check based on SOLUTION_PREFIX
+          resources_to_check=(
+            "aoai-${{ env.SOLUTION_PREFIX }}"
+            "appins-${{ env.SOLUTION_PREFIX }}"
+            "db-cosmos-${{ env.SOLUTION_PREFIX }}"
+            "${{ env.SOLUTION_PREFIX }}-plan"
+            "search-${{ env.SOLUTION_PREFIX }}"
+            "webapp-${{ env.SOLUTION_PREFIX }}"
+            "worksp-${{ env.SOLUTION_PREFIX }}"
+          )
+
+          # Get the list of resources in YAML format
+          resource_list=$(az resource list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output yaml)
           
-          # Get the list of KeyVaults in the subscription
-          keyvaults=$(az resource list --resource-type "Microsoft.KeyVault/vaults" --query "[].name" -o tsv)
-
-          if [ -z "$keyvaults" ]; then
-            echo "No KeyVaults found in the subscription."
-            echo "KEYVAULTS=[]" >> $GITHUB_ENV  # If no KeyVaults found, set an empty array
-          else
-            echo "KeyVaults found: $keyvaults"
-
-            # Format the list into an array with proper formatting (no trailing comma)
-            keyvault_array="[" 
-            first=true
-            for kv in $keyvaults; do
-              if [ "$first" = true ]; then
-                keyvault_array="$keyvault_array\"$kv\""
-                first=false
+          # Maximum number of retries and retry intervals
+          max_retries=3
+          retry_intervals=(30 60 120)
+          retries=0
+          
+          while true; do
+            resource_found=false
+            # Iterate through the resources to check
+            for resource in "${resources_to_check[@]}"; do
+              echo "Checking resource: $resource"
+              if echo "$resource_list" | grep -q "name: $resource"; then
+                echo "Resource '$resource' exists in the subscription."
+                resource_found=true
               else
-                keyvault_array="$keyvault_array,\"$kv\""
+                echo "Resource '$resource' does not exist in the subscription."
               fi
             done
-            keyvault_array="$keyvault_array]"
 
-            # Output the formatted array and save it to the environment variable
-            echo "KEYVAULTS=$keyvault_array" >> $GITHUB_ENV
-          fi
+            # If any resource exists, retry
+            if [ "$resource_found" = true ]; then
+              retries=$((retries + 1))
+              if [ "$retries" -ge "$max_retries" ]; then
+                echo "Maximum retry attempts reached. Exiting."
+                break
+              else
+                echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
+                sleep ${retry_intervals[$retries-1]}
+              fi
+            else
+              echo "No resources found. Exiting."
+              break
+            fi
+          done
+
+      - name: Purging the Resources
+        if: success()
+        run: |
+          set -e
+          # Purging resources based on solution prefix
+          echo "Purging resources..."
+
+          # List of resources to purge
+          resources_to_purge=(
+            "aoai-${{ env.SOLUTION_PREFIX }}"
+            "appins-${{ env.SOLUTION_PREFIX }}"
+            "db-cosmos-${{ env.SOLUTION_PREFIX }}"
+            "${{ env.SOLUTION_PREFIX }}-plan"
+            "search-${{ env.SOLUTION_PREFIX }}"
+            "webapp-${{ env.SOLUTION_PREFIX }}"
+            "worksp-${{ env.SOLUTION_PREFIX }}"
+          )
           
+          for resource in "${resources_to_purge[@]}"; do
+            echo "Purging resource: $resource"
+            if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$resource --verbose; then
+              echo "Failed to purge resource: $resource"
+            else
+              echo "Purged the resource: $resource"
+            fi
+          done
+
+          echo "Resource purging completed successfully"
+
+      - name: Delete Bicep Deployment
+        if: success()
+        run: |
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "true" ]; then
+            echo "Resource group exists. Cleaning..."
+            az group delete \
+                --name ${{ env.RESOURCE_GROUP_NAME }} \
+                --yes \
+                --no-wait
+            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
+          else
+            echo "Resource group does not exist."
+          fi
+
       - name: Send Notification on Failure
         if: failure()
         run: |
           RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-      
-          # Construct the email body
+
           EMAIL_BODY=$(cat <<EOF
           {
-            "body": "<p>Dear Team,</p><p>We would like to inform you that the Client Advisor Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
+            "body": "<p>Dear Team,</p><p>We would like to inform you that the Research Assistant Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
           }
           EOF
           )
-      
-          # Send the notification
+
           curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
             -H "Content-Type: application/json" \
             -d "$EMAIL_BODY" || echo "Failed to send notification"
