container changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,17 +46,41 @@ jobs:
           echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
           echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}"
 
-      - name: Deploy ARM Template at Subscription Level
+      - name: Deploy Template at Subscription Level
         id: deploy
         run: |
           set -e
-          echo "Deploying ARM template at the subscription level...."
+          echo "Deploying template at the subscription level...."
           az deployment sub create \
             --location WestUS \
             --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
-            --template-file infrastructure/deployment.json \
-            --parameters HostingPlanName="${{ env.SOLUTION_PREFIX }}-plan"
-            --parameters WorkspaceName="${{ env.SOLUTION_PREFIX }}-plan"
+            --template-file infra/main.bicep \
+            --parameters \
+                authClientId=${{ secrets.AZURE_CLIENT_ID }} \
+                authClientSecret=${{ secrets.AZURE_CLIENT_SECRET }} \
+                environmentName=pri-maintenance \
+                location=NorthCentralUS \
+                principalId=${{ secrets.AZURE_PRINCIPAL_ID }}  # Added Principal ID
+
+      - name: Update Web App Docker Configuration
+        run: |
+          set -e
+          echo "Updating the Web App to use the ACR Docker image..."
+        
+          # Define the resource name and image details
+          webapp_name="${{ env.SOLUTION_PREFIX }}-webapp"  # Replace with your actual WebApp name
+          container_registry="byocgacontainerreg.azurecr.io"
+          image_name="webapp:dev"
+        
+          # Set up Web App with the correct ACR image
+          az webapp config container set \
+            --name $webapp_name \
+            --resource-group rg-pri-maintenance \
+            --docker-custom-image-name "$container_registry/$image_name" \
+            --docker-registry-server-url "https://$container_registry" \
+            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
+            --query "containerSettings" \
+            --output json        
         
       - name: List KeyVaults and Store in Array
         id: list_keyvaults
@@ -90,6 +114,129 @@ jobs:
             echo "KEYVAULTS=$keyvault_array" >> $GITHUB_ENV
           fi
 
+      - name: Delete Bicep Deployment
+        if: success()
+        run: |
+          set -e
+          echo "Deleting the resources from the subscription..."
+          az deployment sub delete \
+            --name ${{ env.SOLUTION_PREFIX }} \
+            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
+            --no-wait
+
+      - name: Wait for resource deletion to complete
+        run: |
+          # List of KeyVaults and additional resources
+          KEYVAULTS="${{ env.KEYVAULTS }}"
+
+          # Remove the surrounding square brackets, if they exist
+          stripped_keyvaults=$(echo "$KEYVAULTS" | sed 's/\[\|\]//g')
+          
+          # Convert the comma-separated string into an array
+          IFS=',' read -r -a resources_to_check <<< "$stripped_keyvaults"
+          
+          # Append new resources to the array
+          resources_to_check+=("${{ env.SOLUTION_PREFIX }}-openai" "${{ env.SOLUTION_PREFIX }}-cogser")
+
+          echo "List of resources to check: ${resources_to_check[@]}"
+
+          # Get the list of resources in YAML format
+          resource_list=$(az resource list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output yaml)
+
+          # Maximum number of retries
+          max_retries=3
+
+          # Retry intervals in seconds (30, 60, 120)
+          retry_intervals=(30 60 120)
+
+          # Retry mechanism to check resources
+          retries=0
+          while true; do
+            resource_found=false
+
+            # Iterate through the resources to check
+            for resource in "${resources_to_check[@]}"; do
+              echo "Checking resource: $resource"
+              if echo "$resource_list" | grep -q "name: $resource"; then
+                echo "Resource '$resource' exists in the subscription."
+                resource_found=true
+              else
+                echo "Resource '$resource' does not exist in the subscription."
+              fi
+            done
+
+            # If any resource exists, retry
+            if [ "$resource_found" = true ]; then
+              retries=$((retries + 1))
+              if [ "$retries" -ge "$max_retries" ]; then
+                echo "Maximum retry attempts reached. Exiting."
+                break
+              else
+                # Wait for the appropriate interval for the current retry
+                echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
+                sleep ${retry_intervals[$retries-1]}
+              fi
+            else
+              echo "No resources found. Exiting."
+              break
+            fi
+          done
+
+      - name: Purging the Resources
+        if: success()
+        run: |
+          set -e 
+          # Define variables
+          OPENAI_COMMON_PART="-openai"
+          openai_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
+          echo "Azure OpenAI: $openai_name"
+
+          MULTISERVICE_COMMON_PART="-cogser"
+          multiservice_account_name="${{ env.SOLUTION_PREFIX }}${MULTISERVICE_COMMON_PART}"
+          echo "Azure MultiService Account: $multiservice_account_name"
+
+          # Purge OpenAI Resource
+          echo "Purging the OpenAI Resource..."
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$openai_name --verbose; then
+            echo "Failed to purge openai resource: $openai_name"
+          else
+            echo "Purged the openai resource: $openai_name"
+          fi
+   
+          # Purge MultiService Account Resource
+          echo "Purging the MultiService Account Resource..."
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$multiservice_account_name --verbose; then
+            echo "Failed to purge multiService account resource: $multiservice_account_name"
+          else
+            echo "Purged the multiService account resource: $multiservice_account_name"
+          fi
+
+          # Ensure KEYVAULTS is properly formatted as a comma-separated string
+          KEYVAULTS="${{ env.KEYVAULTS }}"
+
+          # Remove the surrounding square brackets, if they exist
+          stripped_keyvaults=$(echo "$KEYVAULTS" | sed 's/\[\|\]//g')
+          
+          # Convert the comma-separated string into an array
+          IFS=',' read -r -a keyvault_array <<< "$stripped_keyvaults"
+
+          echo "Using KeyVaults Array..."
+          for keyvault_name in "${keyvault_array[@]}"; do
+            echo "Processing KeyVault: $keyvault_name"
+            # Check if the KeyVault is soft-deleted
+            deleted_vaults=$(az keyvault list-deleted --query "[?name=='$keyvault_name']" -o json --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }})
+
+            # If the KeyVault is found in the soft-deleted state, purge it
+            if [ "$(echo "$deleted_vaults" | jq length)" -gt 0 ]; then
+              echo "KeyVault '$keyvault_name' is soft-deleted. Proceeding to purge..."
+              az keyvault purge --name "$keyvault_name" --no-wait
+            else
+              echo "KeyVault '$keyvault_name' is not soft-deleted. No action taken."
+            fi
+          done
+
+          echo "Resource purging completed successfully"
+      
       - name: Send Notification on Failure
         if: failure()
         run: |
