added quota check features in pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,16 +35,22 @@ jobs:
       - name: Run Quota Check
         id: quota-check
         run: |
+          export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
+          export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
+          export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
           export AZURE_SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
-          export AZURE_LOCATION="northcentralus"
           export GPT_MIN_CAPACITY="130"
-          export TEXT_EMBEDDING_MIN_CAPACITY="30"
+          export COSMOS_DB_MIN_CAPACITY="80"
 
           chmod +x scripts/checkquota.sh
           if ! scripts/checkquota.sh; then
-            echo "QUOTA_FAILED=true" >> $GITHUB_ENV
-            exit 0
+            # If quota check fails due to insufficient quota, set the flag
+            if grep -q "No region with sufficient quota found" scripts/checkquota.sh; then
+              echo "QUOTA_FAILED=true" >> $GITHUB_ENV
+            fi
+            exit 1  # Fail the pipeline if any other failure occurs
           fi
+
 
       - name: Send Notification on Quota Failure
         if: env.QUOTA_FAILED == 'true'
@@ -116,7 +122,7 @@ jobs:
                 ApplicationInsightsName="appins-${{ env.SOLUTION_PREFIX }}" \
                 WebsiteName="webapp-${{ env.SOLUTION_PREFIX }}" \
                 CosmosDBName="db-cosmos-${{ env.SOLUTION_PREFIX }}" \
-                CosmosDBRegion="NorthCentralUS" \
+                CosmosDBRegion="${{ env.AZURE_LOCATION }}" \
                 AzureSearchService="search-${{ env.SOLUTION_PREFIX }}" \
                 AzureOpenAIResource="aoai-${{ env.SOLUTION_PREFIX }}" \
                 WorkspaceName="worksp-${{ env.SOLUTION_PREFIX }}" 
